services:
  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client/src:/app/src
    ports:
      - 5174:5173
    depends_on:
      - server

  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - 8001:8000
    env_file:
      - project.env
    depends_on:
      - database

  database:
    container_name: postgresql_database
    image: postgres:17.5
    restart: unless-stopped
    env_file:
      - project.env

  database-migrations:
    image: flyway/flyway:11.10
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./database-migrations:/flyway/db/migration
    command: -connectRetries=60 -baselineOnMigrate=true migrate
  
  e2e-tests:
    entrypoint: "/bin/true"
    build: e2e-tests
    network_mode: host
    depends_on:
      - client
    volumes:
      - ./e2e-tests/tests:/app/tests
